-- Disable RLS temporarily for ease of development on subscribers
ALTER TABLE IF EXISTS public.subscribers DISABLE ROW LEVEL SECURITY;

-- If you haven't created subscribers yet:
CREATE TABLE IF NOT EXISTS public.subscribers (
    id bigint generated by default as identity primary key,
    email text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.subscribers DISABLE ROW LEVEL SECURITY;

-- Create solutions table
CREATE TABLE IF NOT EXISTS public.solutions (
    id bigint generated by default as identity primary key,
    icon text not null,
    title text not null,
    description text not null,
    display_order integer default 0
);
ALTER TABLE public.solutions DISABLE ROW LEVEL SECURITY;

-- Insert initial solutions using Lucide icon names
INSERT INTO public.solutions (icon, title, description, display_order)
VALUES 
('users', 'Citizen Portal', 'A unified, accessible platform where citizens can access all public services, track requests, and communicate securely.', 1),
('leaf', 'EcoTracker API', 'Real-time monitoring systems for urban environmental metrics to support smart city initiatives and sustainability.', 2),
('bar-chart-3', 'Public Data Hub', 'Transparent, interactive dashboards providing meaningful insights on public spending, service efficiency, and community health.', 3)
ON CONFLICT DO NOTHING;

-- Create impact_stats table
CREATE TABLE IF NOT EXISTS public.impact_stats (
    id bigint generated by default as identity primary key,
    number_text text not null,
    label text not null,
    display_order integer default 0
);
ALTER TABLE public.impact_stats DISABLE ROW LEVEL SECURITY;

-- Insert initial impact stats
INSERT INTO public.impact_stats (number_text, label, display_order)
VALUES 
('2.5M+', 'Citizens Served', 1),
('98%', 'Satisfaction Rate', 2),
('45+', 'Cities Transformed', 3),
('1.2B', 'Operations Optimized', 4)
ON CONFLICT DO NOTHING;
